### ISSUE TITLE
Improve Help

### ISSUE THREAD

**Issue by sundeep-co-in** [transtats/transtats-cli#2]
Help/suggestion should be displayed directly when we type `transtats status` or any other command.

**Comment by spathare21** [comment]
can we have message like "Type 'transtats <command> --help' for help on a specific command."  after options and before commands.

and looks like this message "Usage: transtats [OPTIONS] COMMAND [ARGS]..."  should be "Usage: transtats COMMAND [OPTIONS] [ARGS]..." as we are executing commands like

transtats coverage --help.

**Comment by sundeep-co-in** [comment]
handled by https://github.com/transtats/transtats-cli/pull/8
